#!/bin/bash -e

export CI_BUILD_DIR=${CI_BUILD_DIR:=$TRAVIS_BUILD_DIR}
export CI_COMMIT=${CI_COMMIT:=$TRAVIS_COMMIT}
export CI_BRANCH=${CI_BRANCH:=$TRAVIS_BRANCH}
export CI_TAG=${CI_TAG:=$TRAVIS_TAG}
export CI_SECURE_ENV_VARS=${CI_SECURE_ENV_VARS:=$TRAVIS_SECURE_ENV_VARS}
export CI_PULL_REQUEST=${CI_PULL_REQUEST:=$TRAVIS_PULL_REQUEST}
export CI_PULL_REQUEST_BRANCH=${CI_PULL_REQUEST_BRANCH:=$TRAVIS_PULL_REQUEST_BRANCH}
export CI_COMMIT_RANGE=${CI_COMMIT_RANGE:=$TRAVIS_COMMIT_RANGE}
export CI_REPO_SLUG=${CI_REPO_SLUG:=$TRAVIS_REPO_SLUG}
export CI_UPLOAD_ARTIFACT_ID=${CI_UPLOAD_ARTIFACT_ID:=$( [[ ${CI_PULL_REQUEST} =~ false ]] && echo ${CI_TAG} || echo ${CI_PULL_REQUEST} )}
