platform :ios do
  lane :setup_signing do |options|
    signing_type = options[:type] # "development", "appstore"

    setup_ci if is_ci

    api_key = app_store_connect_api_key(
      key_id: ENV["api_key_id"],
      issuer_id: ENV["issuer_id"],
      key_content: ENV["api_private_key"],
      duration: 1200
    )

    match(
      type: signing_type,
      app_identifier: 'ch.opengis.qfield',
      api_key: api_key
    )
  end

  lane :upload_s3 do
    aws_s3(
      ipa: "/Users/runner/builddir/qfieldIpa/QField.ipa",
      endpoint: "https://sos-ch-dk-2.exo.io",
      app_directory: 'ci-builds/ios/#{ENV["CI_PACKAGE_FILE_SUFFIX"]}'
    )
  end
end
