/***************************************************************************
 qfappexpressioncontextscopesgenerator.h - QfAppExpressionContextScopesGenerator

 ---------------------
 begin                : 26.03.2025
 copyright            : (C) 2025 by Mathieu Pellerin
 email                : mathieu (at) opengis.ch
 ***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#ifndef QFAPPEXPRESSIONCONTEXTSCOPESGENERATOR_H
#define QFAPPEXPRESSIONCONTEXTSCOPESGENERATOR_H

#include "qfcloudutils.h"
#include "qfgnsspositioninformation.h"

#include <QObject>

class QgsExpressionContextScope;

/**
 * \ingroup core
 */
class QfAppExpressionContextScopesGenerator : public QObject
{
    Q_OBJECT

    Q_PROPERTY( QfGnssPositionInformation positionInformation READ positionInformation WRITE setPositionInformation NOTIFY positionInformationChanged )
    Q_PROPERTY( bool positionLocked READ positionLocked WRITE setPositionLocked NOTIFY positionLockedChanged )
    Q_PROPERTY( QfCloudUserInformation cloudUserInformation READ cloudUserInformation WRITE setCloudUserInformation NOTIFY cloudUserInformationChanged )

  public:
    explicit QfAppExpressionContextScopesGenerator( QObject *parent = nullptr );

    /**
     * Returns position information generated by the TransformedPositionSource according to its provider
     */
    QfGnssPositionInformation positionInformation() const;

    /**
     * Sets position information generated by the TransformedPositionSource according to its provider
     * \param positionInformation the position information
     */
    void setPositionInformation( const QfGnssPositionInformation &positionInformation );

    /**
     * Returns whether the position is locked to the GNSS
     */
    bool positionLocked() const;

    /**
     * Sets whether the position is locked to the GNSS
     */
    void setPositionLocked( bool positionLocked );

    /**
     * Returns the current cloud user information
     */
    QfCloudUserInformation cloudUserInformation() const;

    /**
     * Sets the current cloud user information
     * \param cloudUserInformation the cloud user information
     */
    void setCloudUserInformation( const QfCloudUserInformation &cloudUserInformation );

    QList<QgsExpressionContextScope *> generate();

  signals:
    void positionInformationChanged();
    void positionLockedChanged();
    void cloudUserInformationChanged();

  private:
    QfGnssPositionInformation mPositionInformation;
    bool mPositionLocked = false;
    QfCloudUserInformation mCloudUserInformation;
};

#endif // QFAPPEXPRESSIONCONTEXTSCOPESGENERATOR_H
