set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_VERSION 7.0)
set(VCPKG_CXX_FLAGS "-D_WIN32_WINNT=0x0601")
set(VCPKG_C_FLAGS "-D_WIN32_WINNT=0x0601")

set(VCPKG_BUILD_TYPE release)