name: 🧹 Static Tests

on:
  push:
    branches:
      - master
      - release-**
  pull_request:
    branches:
      - master
      - release-**

jobs:
  #  license_check:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout
  #        uses: actions/checkout@v6
  #      - name: Install Requirements
  #        run: |
  #          sudo apt install -y \
  #              cpanminus
  #            cpanm --notest App::Licensecheck
  #
  #      - name: Run License Check
  #        run: ./scripts/test_licenses.sh

  banned_keywords_check:
    name: banned keywords check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run Banned Keywords Test
        run: ./scripts/test_banned_keywords.sh

  cppcheck-1_9:
    name: cpp check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Requirements
        run: |
          sudo apt install -y cppcheck
      - name: Run cppcheck test
        run: ./scripts/cppcheck.sh

  url_check:
    name: URLs check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check QField URLs
        uses: nirvn/check-urls@main
        with:
          search_path: ./
          search_regexp: https://[A-Za-z\.]+qfield.(cloud|org)[^ <>\\\"')]+
          skip_urls: |
            https://app.qfield.cloud/settings/%1/billing
            https://docs.qfield.org/%1
            https://qfield.cloud/some-new-ignored-url
